name: "Reindex Algolia"
author: "Cloud Posse"
description: "Reindex Algolia"
#outputs:
#  has_updated_sources:
#    description: "0 if no source file has been updated, 1 if source files has been updated"
runs:
  using: "docker"
  #image: "docker://cloudposse/build-harness:0.5.5"
  #image: "${steps.prepare.outputs.first_tag}"
  #image: "${INPUT_CONTAINER_NAME}"
  image: "Dockerfile"
  entrypoint: "/entrypoint.sh"
branding:
  icon: "check"
  color: "green"
