name: 'Publish GitHub Pages'
description: 'Publish the Hugo-based Cloud Posse docs website to GitHub Pages.'
inputs:
  content:
    description: 'Comma-separated list of directories in the top level of the repo that contains documentation'
    required: true
  hugo_url:
    description: 'URL of the Hugo site after deployment'
    required: true
  github_pages_push_path:
    description: 'Location where the repo/branch that deploys to GitHub Pages will be cloned'
    required: true
  github_pages_pull_branch:
    description: 'The branch of the repo which contains the documentation'
    required: true
  github_pages_repo:
    description: 'Repo containing documentation to be deployed to GitHub Pages'
    required: true
  github_pages_push_branch:
    description: 'The branch of the repo which GitHub Pages will deploy from'
    required: true
  css:
    description: 'Custom CSS to customize the look and feel'
    required: false
  config:
    description: 'Hugo YAML configuration overrides'
    required: false
  debug:
    description: 'Toggle to turn on debug functionality'
    required: false
  hugo_content:
    description: 'Folders of generic documentation to build into the final docs website'
    required: false
    default: "tutorials,howto,fundamentals,reference"
  hugo_publish_dir:
    description: >
      Directory within the staging directory that the built Hugo website files will be written to
    required: false
    default: "docs"
  hugo_config:
    description: 'Location of to-be-written Hugo config file (actual location not important)'
    required: false
    default: "hugo.config.new.yml"
  htmltest_config:
    description: 'Location to write the htmltest config file (actual location not important)'
    required: false
    default: ".htmltest.new.yml"
  hugo_repo:
    description: 'Repo containing Hugo build files'
    required: false
    default: "https://github.com/cloudposse/docs"
  hugo_branch:
    description: 'Branch of hugo_repo containing Hugo build files'
    required: false
    default: "master"
  github_pages_hugo_path:
    description: 'Location where the repo containing the Hugo files will be cloned'
    required: false
    default: "/tmp/hugo"
  github_pages_pull_path:
    description: 'Location where the repo/branch containing the raw documentation will be cloned'
    required: false
    default: "/tmp/pull"
  staging_dir:
    description: >
      Directory where all documentation files will be combined with Hugo configuration files, and
      the Hugo site will be built
    required: false
    default: "/tmp/staging"
runs:
  using: 'composite'
  steps:
    - name: "Checkout All Repos"
      run: |
        # Check out
        # 1) Essential Hugo build tools
        git clone --branch ${HUGO_BRANCH} $HUGO_REPO $GITHUB_PAGES_HUGO_PATH
        # 2) Site-specific documentation
        git clone --branch $GITHUB_PAGES_PULL_BRANCH $GITHUB_PAGES_REPO $GITHUB_PAGES_PULL_PATH
        # 3) The GitHub Pages deployment branch for this site
        git clone --branch $GITHUB_PAGES_PUSH_BRANCH $GITHUB_PAGES_REPO $GITHUB_PAGES_PUSH_PATH
      shell: bash
      env:
        HUGO_REPO: ${{ inputs.hugo_repo }}
        HUGO_BRANCH: ${{ inputs.hugo_branch }}
        GITHUB_PAGES_HUGO_PATH: ${{ inputs.github_pages_hugo_path }}
        GITHUB_PAGES_REPO: ${{ inputs.github_pages_repo }}
        GITHUB_PAGES_PULL_PATH: ${{ inputs.github_pages_pull_path }}
        GITHUB_PAGES_PULL_BRANCH: ${{ inputs.github_pages_pull_branch }}
        GITHUB_PAGES_PUSH_PATH: ${{ inputs.github_pages_push_path }}
        GITHUB_PAGES_PUSH_BRANCH: ${{ inputs.github_pages_push_branch }}
    - name: "Collate Documentation Files"
      run: pip install GitPython pyyaml && python collate.py
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        GITHUB_PAGES_HUGO_PATH: ${{ inputs.github_pages_hugo_path }}
        STAGING_DIR: ${{ inputs.staging_dir }}
        DEBUG: ${{ inputs.debug }}
        CONTENT: ${{ inputs.content }}
        HUGO_CONTENT: ${{ inputs.hugo_content }}
    - name: "Append Custom CSS"
      run: echo -e "$CSS" >> ./themes/cloudposse/src/scss/custom.scss
      shell: bash
      working-directory: ${{ inputs.staging_dir }}
      env:
        CSS: ${{ inputs.css }}
    - name: "Customize Hugo YAML Config"
      run: |
        curl -1sLf 'https://dl.cloudsmith.io/public/cloudposse/packages/setup.deb.sh' | sudo bash
        sudo apt-get install yq
        echo "config: $CONFIG"
        for SUBSTITUTION in $CONFIG
        do
          echo $SUBSTITUTION
          yq e -i $SUBSTITUTION config.yaml
        done
        echo "catting config.yaml:"
        cat config.yaml
      shell: bash
      working-directory: ${{ inputs.staging_dir }}
      env:
        CONFIG: ${{ inputs.config }}
    - name: "Build Hugo Site Locally"
      run: |
        docker build -t cloudposse/docs .
        make release
        make real-clean hugo/build
      shell: bash
      working-directory: ${{ inputs.staging_dir }}
      env:
        HUGO_URL: ${{ inputs.hugo_url }}
        HUGO_PUBLISH_DIR: ${{ inputs.hugo_publish_dir }}
        HUGO_CONFIG: ${{ inputs.hugo_config }}
        HTMLTEST_CONFIG: ${{ inputs.htmltest_config }}
    - name: "Move Hugo Site Files to Publishing Directory"
      run: cp -r ./${HUGO_PUBLISH_DIR} ${GITHUB_PAGES_PUSH_PATH}
      shell: bash
      working-directory: ${{ inputs.staging_dir }}
      env:
        HUGO_PUBLISH_DIR: ${{ inputs.hugo_publish_dir }}
        GITHUB_PAGES_PUSH_PATH: ${{ inputs.github_pages_push_path }}
