name: 'Publish GitHub Pages'
description: 'Publish the Hugo-based Cloud Posse docs website to GitHub Pages.'
inputs:
  CONTENT: 'None'
  DEBUG: 'False'
  HUGO_URL: 'None'
  HUGO_PUBLISH_DIR: 'None'
  HUGO_CONFIG: 'None'
  HTMLTEST_CONFIG: 'None'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
runs:
  using: 'composite'
  steps:
    - run: PYTHON_SCRIPT_LOCATION=${{ github.action_path }} ${{ github.action_path}}/entrypoint.sh
      shell: bash
