name: 'Publish GitHub Pages'
description: 'Publish the Hugo-based Cloud Posse docs website to GitHub Pages.'
inputs:
  content:
    description: 'Comma-separated list of directories in the top level of the repo that contains documentation'
    required: true
  css:
    description: 'Custom CSS to customize the look and feel'
    required: true
  debug:
    description: 'Toggle to turn on debug functionality'
    required: true
  hugo_url:
    description: 'URL of the Hugo site after deployment'
    required: true
  hugo_publish_dir:
    description: 'Directory in the repo that GitHub Pages will deploy to'
    required: true
  hugo_config:
    description: 'Location of to-be-written Hugo config file (actual location not important)'
    required: true
  htmltest_config:
    description: 'Location to write the htmltest config file (actual location not important)'
    required: true
  github_pages_hugo_path:
    description: 'Location where the repo containing the Hugo files will be cloned'
    required: true
  github_pages_pull_branch:
    description: 'The branch of the repo which contains the documentation'
    required: true
  staging_dir:
    description: 'Directory to collate all docs and Hugo configuration files'
    required: true
  github_pages_repo:
    description: 'Repo containing documentation to be deployed to GitHub Pages'
    required: true
  github_pages_push_branch:
    description: 'The branch of the repo which GitHub Pages will deploy to'
    required: true
  github_pages_directory:
    description: 'The directory to write the rendered website files to (should not be an absolute path)'
    required: true
runs:
  using: 'composite'
  steps:
    - name: "Checkout All Repos"
      run: |
        pip install GitPython pyyaml
        python -c 'from checkout_and_collate import *; checkout_repos()'
      shell: bash
      env:
        PYTHONPATH: ${{ github.action_path }}
        GITHUB_PAGES_PUSH_PATH: ${{ github.action_path }}/${{ inputs.github_pages_directory }}
        GITHUB_PAGES_PULL_BRANCH: ${{ inputs.github_pages_pull_branch }}
        GITHUB_PAGES_HUGO_PATH: ${{ inputs.github_pages_hugo_path }}
        DEBUG: ${{ inputs.debug }}
        STAGING_DIR: ${{ inputs.staging_dir }}
    - name: "Append Custom CSS"
      run: echo -e "$CSS" >> ${GITHUB_PAGES_HUGO_PATH}/themes/cloudposse/src/scss/custom.scss
      shell: bash
      env:
        CSS: ${{ inputs.css }}
        GITHUB_PAGES_HUGO_PATH: ${{ inputs.github_pages_hugo_path }}
    - name: "Collate Documentation Files"
      run: |
        pip install GitPython pyyaml
        python -c 'from checkout_and_collate import *; collate_files()'
      shell: bash
      env:
        PYTHONPATH: ${{ github.action_path }}
        GITHUB_PAGES_PUSH_PATH: ${{ github.action_path }}/${{ inputs.github_pages_directory }}
        GITHUB_PAGES_HUGO_PATH: ${{ inputs.github_pages_hugo_path }}
        GITHUB_PAGES_PULL_BRANCH: ${{ inputs.github_pages_pull_branch }}
        DEBUG: ${{ inputs.debug }}
        CONTENT: ${{ inputs.content }}
        STAGING_DIR: ${{ inputs.staging_dir }}
    - name: "Build Hugo Site Locally"
      run: |
        docker build -t cloudposse/docs .
        make release
        make real-clean hugo/build
      shell: bash
      working-directory: ${{ inputs.staging_dir }}
      env:
        HUGO_URL: ${{ inputs.hugo_url }}
        HUGO_PUBLISH_DIR: ${{ inputs.hugo_publish_dir }}
        HUGO_CONFIG: ${{ inputs.hugo_config }}
        HTMLTEST_CONFIG: ${{ inputs.htmltest_config }}
    - name: "Move Hugo Site Files to Publishing Directory"
      run: cp -r ${STAGING_DIR}/${HUGO_PUBLISH_DIR} ${GITHUB_PAGES_PUSH_PATH}
      shell: bash
      env:
        STAGING_DIR: ${{ inputs.staging_dir }}
        HUGO_PUBLISH_DIR: ${{ inputs.hugo_publish_dir }}
        GITHUB_PAGES_PUSH_PATH: ${{ github.action_path }}/${{ inputs.github_pages_directory }}
