name: 'Publish GitHub Pages'
description: 'Publish the Hugo-based Cloud Posse docs website to GitHub Pages.'
inputs:
  CONTENT:
    description: 'comma-separated list of directories in the top level of the repo that contains documentation'
    required: false
  DEBUG:
    description: 'whether to turn on debug printouts/functionality'
    required: false
  HUGO_URL:
    description: 'URL of the Hugo site after deployment'
    required: false
  HUGO_PUBLISH_DIR:
    description: 'directory in the repo that GitHub Pages will deploy to'
    required: false
  HUGO_CONFIG:
    description: 'location of to-be-written Hugo config file (actual location not important)'
    required: false
  HTMLTEST_CONFIG:
    description: 'location of to-be-written htmltest config file (actual location not important)'
    required: false
  GITHUB_TOKEN:
    description: 'github token'
    required: false
  GITHUB_ACTOR:
    description: 'github actor'
    required: false
  GITHUB_PAGES_REPO:
    description: 'repo containing documentation to be deployed to GitHub Pages'
    required: false
  GITHUB_PAGES_PULL_BRANCH:
    description: 'the branch of the repo which contains the documentation'
    required: false
  GITHUB_PAGES_PUSH_BRANCH:
    description: 'the branch of the repo which GitHub Pages will deploy to'
    required: false
  GITHUB_PAGES_DIRECTORY:
    description: 'the directory to write the rendered website files to (should not be an absolute path)'
    required: false
runs:
  using: 'composite'
  steps:
    - run: PYTHON_SCRIPT_LOCATION=${{ github.action_path }} ${{ github.action_path}}/entrypoint.sh
      shell: bash
      env:
        INPUT_CONTENT: ${{ inputs.CONTENT }}
        INPUT_DEBUG: ${{ inputs.DEBUG }}
        INPUT_HUGO_URL: ${{ inputs.HUGO_URL }}
        INPUT_HUGO_PUBLISH_DIR: ${{ inputs.HUGO_PUBLISH_DIR }}
        INPUT_HUGO_CONFIG: ${{ inputs.HUGO_CONFIG }}
        INPUT_HTMLTEST_CONFIG: ${{ inputs.HTMLTEST_CONFIG }}
        INPUT_GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        INPUT_GITHUB_ACTOR: ${{ inputs.GITHUB_ACTOR }}
        INPUT_GITHUB_PAGES_REPO: ${{ inputs.GITHUB_PAGES_REPO }}
        INPUT_GITHUB_PAGES_PULL_BRANCH: ${{ inputs.GITHUB_PAGES_PULL_BRANCH }}
        INPUT_GITHUB_PAGES_PUSH_BRANCH: ${{ inputs.GITHUB_PAGES_PUSH_BRANCH }}
        INPUT_GITHUB_PAGES_DIRECTORY: ${{ inputs.GITHUB_PAGES_DIRECTORY }}
