name: 'Publish GitHub Pages'
description: 'Publish the Hugo-based CloudPosse docs website to GitHub Pages.'
runs:
  using: 'composite'
  steps:
#    - uses: actions/setup-python@v2
#      with:
#        python-version: '3.x'
    - run: |
        pip install GitPython
        python ${{ github.action_path }}/entrypoint.py
        printenv
        cd $STAGING_DIR && pwd && ls -ahlrt . && ls -ahlrt ${STAGING_DIR} && make release && make real-clean hugo/build
        cp -r ${STAGING_DIR}/${HUGO_PUBLISH_DIR} $GITHUB_PAGES_PUSH_PATH
      shell: bash
