name: github-pages-deployment
on:
  push:
    branches:
    - master
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types:
    - published

defaults:
  run:
    shell: bash +e -x -o pipefail {0}

jobs:
  github-pages-deploy:
    name: "Build Hugo Site and Deploy to GitHub Pages"
    runs-on: ubuntu-latest
    env:
      GITHUB_PAGES_REPO: https://github.com/cloudposse/docs
      GITHUB_PAGES_PUSH_BRANCH: production
      GITHUB_PAGES_PUSH_PATH: github_pages
    steps:
    - name: "Checkout source code at current commit"
      uses: actions/checkout@v2
    - name: "Build Documentation Website Locally"
      uses: cloudposse/docs/actions/publish-github-pages@publish-gh-pages-python
      with:
        content: docs,modules
        config: |
          .baseURL=test.url
          .enableEmoji="absolutely"
        hugo_url: https://cloudposse.github.io/docs
        github_pages_pull_branch: master
        github_pages_repo: ${{ env.GITHUB_PAGES_REPO }}
        github_pages_push_branch: ${{ env.GITHUB_PAGES_PUSH_BRANCH }}
        github_pages_push_path: ${{ env.GITHUB_PAGES_PUSH_PATH }}
    - name: "Deploy Documentation Website to GitHub Pages"
      uses: cloudposse/actions/github/git-push@0.30.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        GITHUB_REPOSITORY: ${{ env.GITHUB_PAGES_REPO }}
        GIT_DIRECTORY: ${{ env.GITHUB_PAGES_PUSH_PATH }}
        GIT_BRANCH: ${{ env.GITHUB_PAGES_PUSH_BRANCH }}
